name: codex_env_py312
channels:
  - defaults
dependencies:
  - python=3.12.10
  - pip
  - pip:
  - black==25.1.0
  - click==8.2.1
  - filelock==3.18.0
  - fsspec==2025.7.0
  - iniconfig==2.1.0
  - isort==6.0.1
  - jinja2==3.1.6
  - MarkupSafe==3.0.2
  - mpmath==1.3.0
  - mypy==1.16.1
  - mypy_extensions==1.1.0
  - networkx==3.5
  - nodeenv==1.9.1
  - nvidia-cublas-cu12==12.6.4.1
  - nvidia-cuda-cupti-cu12==12.6.80
  - nvidia-cuda-nvrtc-cu12==12.6.77
  - nvidia-cuda-runtime-cu12==12.6.77
  - nvidia-cudnn-cu12==9.5.1.17
  - nvidia-cufft-cu12==11.3.0.4
  - nvidia-cufile-cu12==1.11.1.6
  - nvidia-curand-cu12==10.3.7.77
  - nvidia-cusolver-cu12==11.7.1.2
  - nvidia-cusparse-cu12==12.5.4.2
  - nvidia-cusparselt-cu12==0.6.3
  - nvidia-nccl-cu12==2.26.2
  - nvidia-nvjitlink-cu12==12.6.85
  - nvidia-nvtx-cu12==12.6.77
  - packaging==25.0
  - pathspec==0.12.1
  - platformdirs==4.3.8
  - pluggy==1.6.0
  - Pygments==2.19.2
  - pyright==1.1.403
  - pytest==8.4.1
  - ruff==0.12.2
  - setuptools==80.9.0
  - sympy==1.14.0
  - torch==2.7.1
  - triton==3.3.1
  - typing_extensions==4.14.1
