channels:
  - conda-forge
  - defaults

name: codex_env_py311
dependencies:
  - python=3.11.12
  - pip:
      - black==25.1.0
      - click==8.2.1
      - filelock==3.18.0
      - fsspec==2025.7.0
      - iniconfig==2.1.0
      - isort==6.0.1
      - jinja2==3.1.6
      - MarkupSafe==3.0.2
      - mpmath==1.3.0
      - packaging==25.0
      - pathspec==0.12.1
      - platformdirs==4.3.8
      - pluggy==1.6.0
      - Pygments==2.19.2
      - pyright==1.1.403
      - pytest==8.4.1
      - ruff==0.12.2
      - setuptools==80.9.0
      - sympy==1.14.0
      - torch==2.7.1
      - torchvision==0.22.1
      - torchaudio==2.7.1
      - triton==3.3.1
      - typing_extensions==4.14.1
