name: hinet_pytorch2
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.9
  - pytorch=2.7.1
  - torchvision=0.22.1
  - torchaudio=2.7.1
  - cudatoolkit=11.8
  - pip
  - pip:
      - matplotlib
      - numpy
      - opencv-python
      - tqdm

